// script_manager.js - Manages saving, editing, toggling, and running userscripts

const ScriptManager = {
  STORAGE_KEY: 'saved_userscripts',

  /**
   * Fetch all saved userscripts from storage.
   * @returns {Promise<Array>}
   */
  async getAllScripts() {
    if (typeof chrome !== 'undefined' && chrome.storage && chrome.storage.local) {
      const data = await chrome.storage.local.get(this.STORAGE_KEY);
      return data[this.STORAGE_KEY] || [];
    }
    try {
      const raw = localStorage.getItem(this.STORAGE_KEY);
      return raw ? JSON.parse(raw) : [];
    } catch (e) {
      return [];
    }
  },

  async _saveAll(scripts) {
    if (typeof chrome !== 'undefined' && chrome.storage && chrome.storage.local) {
      await chrome.storage.local.set({ [this.STORAGE_KEY]: scripts });
    } else {
      try {
        localStorage.setItem(this.STORAGE_KEY, JSON.stringify(scripts));
      } catch (e) {}
    }
  },

  /**
   * Parse Tampermonkey / Greasemonkey metadata header block from script code.
   * @param {string} code
   * @returns {Object}
   */
  parseMetadata(code) {
    const meta = {
      name: '',
      description: '',
      matchPatterns: [],
      runAt: 'document_idle',
      version: '',
      author: '',
      grants: []
    };

    if (!code || typeof code !== 'string') return meta;

    // Extract content inside // ==UserScript== ... // ==/UserScript==
    const blockMatch = code.match(/\/\/\s*==UserScript==([\s\S]*?)\/\/\s*==\/UserScript==/i);
    const block = blockMatch ? blockMatch[1] : code;

    const lines = block.split(/\r?\n/);
    for (const rawLine of lines) {
      const line = rawLine.trim();
      const match = line.match(/^\/\/\s*@([a-zA-Z0-9_-]+)(?:\s+(.*))?$/);
      if (!match) continue;

      const tag = match[1].toLowerCase();
      const val = (match[2] || '').trim();

      if (tag === 'name' && !meta.name && val) {
        meta.name = val;
      } else if (tag === 'description' && !meta.description && val) {
        meta.description = val;
      } else if ((tag === 'match' || tag === 'include') && val) {
        if (!meta.matchPatterns.includes(val)) {
          meta.matchPatterns.push(val);
        }
      } else if (tag === 'run-at' || tag === 'runat') {
        if (val) meta.runAt = val.replace('-', '_');
      } else if (tag === 'version' && val) {
        meta.version = val;
      } else if (tag === 'author' && val) {
        meta.author = val;
      } else if (tag === 'grant' && val) {
        meta.grants.push(val);
      }
    }

    return meta;
  },

  /**
   * Format a script with standard Tampermonkey // ==UserScript== header block.
   * If code already contains a header, it is returned untouched.
   * @param {Object} script
   * @param {string} defaultDomain
   * @returns {string}
   */
  formatAsUserScript(script, defaultDomain = '<all_urls>') {
    const code = (script?.code || '').trim();
    if (/\/\/\s*==UserScript==[\s\S]*?\/\/\s*==\/UserScript==/i.test(code)) {
      return script.code;
    }

    const name = script?.name || 'New Userscript';
    const desc = script?.description || 'Custom DOM modifier generated by Userscript Agent';
    let patterns = Array.isArray(script?.matchPatterns) && script.matchPatterns.length > 0
      ? script.matchPatterns
      : [defaultDomain];

    const lines = [
      '// ==UserScript==',
      `// @name         ${name}`,
      '// @namespace    http://tampermonkey.net/',
      `// @version      ${new Date().toISOString().slice(0, 10)}`,
      `// @description  ${desc}`,
      '// @author       Userscript AI Agent'
    ];

    for (const p of patterns) {
      lines.push(`// @match        ${p}`);
    }

    lines.push('// @icon         https://www.google.com/s2/favicons?sz=64&domain=example.com');
    lines.push(`// @run-at       ${(script?.runAt || 'document_idle').replace('_', '-')}`);
    lines.push('// @grant        none');
    lines.push('// ==/UserScript==');
    lines.push('');

    if (code) {
      lines.push(code);
    } else {
      lines.push('(function() {');
      lines.push("    'use strict';");
      lines.push('');
      lines.push('    // Write your custom DOM modifications here...');
      lines.push('})();');
    }

    return lines.join('\n');
  },

  /**
   * Save or update a userscript.
   * Automatically extracts name, description, matchPatterns, and runAt from code metadata if not explicitly provided.
   * @param {Object} script
   */
  async saveScript(script) {
    const scripts = await this.getAllScripts();
    const existingIndex = scripts.findIndex((s) => s.id === script.id);

    const now = Date.now();
    const code = script.code || '';
    const parsedMeta = this.parseMetadata(code);

    const name = script.name || parsedMeta.name || 'Untitled Userscript';
    const description = script.description || parsedMeta.description || '';

    let matchPatterns = script.matchPatterns;
    if (!matchPatterns || (Array.isArray(matchPatterns) && matchPatterns.length === 0)) {
      matchPatterns = parsedMeta.matchPatterns.length > 0 ? parsedMeta.matchPatterns : ['<all_urls>'];
    } else if (!Array.isArray(matchPatterns)) {
      matchPatterns = [matchPatterns];
    }

    const runAt = script.runAt || parsedMeta.runAt || 'document_idle';

    const scriptToSave = {
      id: script.id || `script_${now}_${Math.random().toString(36).slice(2, 7)}`,
      name,
      description,
      matchPatterns,
      code,
      enabled: script.enabled !== undefined ? script.enabled : true,
      runAt,
      createdAt: script.createdAt || now,
      updatedAt: now
    };

    if (existingIndex >= 0) {
      scripts[existingIndex] = scriptToSave;
    } else {
      scripts.unshift(scriptToSave);
    }

    await this._saveAll(scripts);
    return scriptToSave;
  },

  /**
   * Delete a script by ID.
   * @param {string} id
   */
  async deleteScript(id) {
    let scripts = await this.getAllScripts();
    scripts = scripts.filter((s) => s.id !== id);
    await this._saveAll(scripts);
    return true;
  },

  /**
   * Toggle enabled status of a script.
   * @param {string} id
   * @param {boolean} enabled
   */
  async toggleScript(id, enabled) {
    const scripts = await this.getAllScripts();
    const target = scripts.find((s) => s.id === id);
    if (target) {
      target.enabled = enabled;
      target.updatedAt = Date.now();
      await this._saveAll(scripts);
      return target;
    }
    return null;
  },

  /**
   * Execute a script directly in the specified tab.
   * @param {number} tabId
   * @param {string} code
   * @param {string} name
   */
  async executeInTab(tabId, code, name = 'Script') {
    try {
      const results = await chrome.scripting.executeScript({
        target: { tabId },
        world: 'MAIN',
        func: (scriptCode, scriptName) => {
          try {
            let res;
            try {
              const runner = new Function(scriptCode);
              res = runner();
            } catch (evalErr) {
              // CSP fallback if host page restricts new Function
              const s = document.createElement('script');
              s.textContent = scriptCode;
              (document.head || document.documentElement).appendChild(s);
              s.remove();
              res = 'Executed via script tag injection';
            }
            console.log(`[Userscript AI Agent] Executed "${scriptName}" successfully:`, res);
            return { success: true, result: res !== undefined ? String(res) : 'Executed successfully' };
          } catch (err) {
            console.error(`[Userscript AI Agent] Execution error in "${scriptName}":`, err);
            return { success: false, error: err.message, stack: err.stack };
          }
        },
        args: [code, name]
      });

      return results?.[0]?.result || { success: true };
    } catch (err) {
      return { success: false, error: err.message };
    }
  },

  /**
   * Convert Tampermonkey or Chrome match pattern to RegExp.
   * Supports apex domains, subdomains (*.domain.com), schemes, and paths.
   * @param {string} pattern
   * @returns {RegExp|null}
   */
  patternToRegExp(pattern) {
    if (!pattern || typeof pattern !== 'string') return null;
    pattern = pattern.trim();
    if (pattern === '<all_urls>' || pattern === '*' || pattern === '*://*/*') {
      return /^https?:\/\/.+/i;
    }

    let scheme = 'https?';
    let rest = pattern;
    if (pattern.startsWith('*://')) {
      scheme = 'https?';
      rest = pattern.slice(4);
    } else if (pattern.startsWith('http://')) {
      scheme = 'http';
      rest = pattern.slice(7);
    } else if (pattern.startsWith('https://')) {
      scheme = 'https';
      rest = pattern.slice(8);
    } else if (pattern.startsWith('*')) {
      scheme = 'https?';
      rest = pattern.slice(1);
      if (rest.startsWith('://')) rest = rest.slice(3);
    }

    const slashIdx = rest.indexOf('/');
    let host = slashIdx !== -1 ? rest.slice(0, slashIdx) : rest;
    let path = slashIdx !== -1 ? rest.slice(slashIdx) : '/*';

    let hostRegex = '';
    if (host === '*' || host === '') {
      hostRegex = '[^/]+';
    } else if (host.startsWith('*.')) {
      const domain = host.slice(2).replace(/([.+?^=!:${}()|[\]/\\])/g, '\\$1');
      // Matches apex domain (archive.ph) and any subdomain (www.archive.ph, sub.archive.ph)
      hostRegex = '(?:[a-zA-Z0-9-]+\\.)*' + domain;
    } else {
      const escaped = host.replace(/([.+?^=!:${}()|[\]/\\])/g, '\\$1').replace(/\*/g, '[a-zA-Z0-9-]+');
      hostRegex = '(?:[a-zA-Z0-9-]+\\.)*' + escaped;
    }

    const pathRegex = path
      .replace(/([.+?^=!:${}()|[\]/\\])/g, '\\$1')
      .replace(/\*/g, '.*');

    return new RegExp('^' + scheme + ':\\/\\/' + hostRegex + (pathRegex ? pathRegex : '.*') + '$', 'i');
  },

  /**
   * Check if a URL matches any pattern in a list.
   * @param {string} url
   * @param {Array<string>} patterns
   */
  matchesUrl(url, patterns) {
    if (!url || !patterns) return false;
    if (!Array.isArray(patterns)) patterns = [patterns];

    for (let pattern of patterns) {
      if (!pattern) continue;
      try {
        const rx = this.patternToRegExp(pattern);
        if (rx && rx.test(url)) return true;
      } catch (e) {
        console.warn('Pattern regex test failed for:', pattern, e);
      }
    }
    return false;
  },

  /**
   * Export all scripts as JSON string.
   */
  async exportScripts() {
    const scripts = await this.getAllScripts();
    return JSON.stringify(
      {
        exportedAt: new Date().toISOString(),
        generator: 'Userscript AI Agent (Alibaba Page-Agent style)',
        scripts
      },
      null,
      2
    );
  },

  /**
   * Import scripts from JSON string (supports Tampermonkey / agent backup) or raw .user.js string.
   * @param {string} rawContent
   */
  async importScripts(rawContent) {
    try {
      let scriptsToImport = [];

      // Try parsing as JSON (backup from agent or Tampermonkey export)
      try {
        const data = JSON.parse(rawContent);
        scriptsToImport = Array.isArray(data) ? data : data.scripts || [];
      } catch (jsonErr) {
        // If not JSON, check if it's a raw .user.js / .js / .txt userscript file
        if (typeof rawContent === 'string' && rawContent.trim().length > 0) {
          const meta = this.parseMetadata(rawContent);
          scriptsToImport = [
            {
              id: `script_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`,
              name: meta.name || 'Imported Userscript',
              description: meta.description || '',
              matchPatterns: meta.matchPatterns.length > 0 ? meta.matchPatterns : ['<all_urls>'],
              code: rawContent,
              enabled: true,
              runAt: meta.runAt || 'document_idle'
            }
          ];
        }
      }

      if (!Array.isArray(scriptsToImport) || scriptsToImport.length === 0) {
        throw new Error('No valid userscripts found in file.');
      }

      const current = await this.getAllScripts();
      let importedCount = 0;

      for (const item of scriptsToImport) {
        if (!item.code && !item.source) continue;
        const code = item.code || item.source || '';
        const meta = this.parseMetadata(code);

        const newScript = {
          id: item.id || `script_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`,
          name: item.name || item.title || meta.name || 'Imported Userscript',
          description: item.description || meta.description || '',
          matchPatterns: item.matchPatterns || item.matches || (meta.matchPatterns.length > 0 ? meta.matchPatterns : ['<all_urls>']),
          code: code,
          enabled: item.enabled !== undefined ? item.enabled : true,
          runAt: item.runAt || meta.runAt || 'document_idle',
          createdAt: item.createdAt || Date.now(),
          updatedAt: Date.now()
        };

        const existingIdx = current.findIndex((s) => s.id === newScript.id || s.name === newScript.name);
        if (existingIdx >= 0) {
          current[existingIdx] = newScript;
        } else {
          current.unshift(newScript);
        }
        importedCount++;
      }

      await this._saveAll(current);
      return { success: true, count: importedCount };
    } catch (e) {
      return { success: false, error: e.message };
    }
  }
};

window.ScriptManager = ScriptManager;
